#!/bin/bash

# Adapted from https://github.com/rossf7/label-schema-automated-build/blob/master/hooks/build
# on 2018-11-07

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             -t $IMAGE_NAME .
